version: '3.8'

services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${RAILWAY_TCP_PROXY_DOMAIN}
      - DB_POSTGRESDB_PORT=${RAILWAY_TCP_PROXY_PORT}
      - DB_POSTGRESDB_DATABASE=${PGDATABASE}
      - DB_POSTGRESDB_USER=${PGUSER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
